### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kawet00** [HideakiAtsuyo/Discord-Protector#2]
Hello I have question what does this protect?

**Comment by HideakiAtsuyo** [comment]
> Hello I have question what does this protect?

I will probably update it later atm I don't have any motivation but it will protect Discord without any useless protection.

**Comment by Kawet00** [comment]
And the other projects abour discord protect they are optional or it's just other projects?

**Comment by HideakiAtsuyo** [comment]
> And the other projects abour discord protect they are optional or it's just other projects?

What do you mean ?

**Comment by Kawet00** [comment]
For exemple: Discord-Injections-Remover

**Comment by HideakiAtsuyo** [comment]
> For exemple: Discord-Injections-Remover

It was the old code, in C#, this one will be fully in C++, I just don't know if I will provide it open-src or closed-src to avoid people to check the code to counter it etc..

**Comment by Kawet00** [comment]
I see I see so the best is the Discord-Protector or the other

**Comment by HideakiAtsuyo** [comment]
> I see I see so the best is the Discord-Protector or the other

Discord-Protector is a port of Discord-Injections-Rempver in C++ to avoid people to easly understand how it work when it's built, but it will also be updated to block more way to get token grabbed or infected :)

**Comment by Kawet00** [comment]
ok ok and who it work?

**Comment by HideakiAtsuyo** [comment]
> ok ok and who it work?

"Who" it work ?

**Comment by Kawet00** [comment]
how* sry

**Comment by HideakiAtsuyo** [comment]
> how* sry

Actually just verifying the content of some places but later it will have more features, just in case I make it closed-src I will not tell you every features but it will be good enough

**Comment by Kawet00** [comment]
ok

**Comment by Kawet00** [comment]
and how I need to do to install it?

**Comment by HideakiAtsuyo** [comment]
> and how I need to do to install it?

For this one you need to compile it or download the pre-release but later an installer will be made :)

**Comment by Kawet00** [comment]
ok
